#!/usr/bin/env bash
set -euo pipefail

# Build iPXE / syslinux boot assets for ISO export.
# Intended to run in GitHub Actions (Linux), not on the Windows control laptop.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/assets}"
mkdir -p "$OUT"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> cloning iPXE"
git clone --depth 1 https://github.com/ipxe/ipxe.git "$WORKDIR/ipxe"

# Enable file:// so EFI binary can chain embed.ipxe on the ISO
mkdir -p "$WORKDIR/ipxe/src/config/local"
cat > "$WORKDIR/ipxe/src/config/local/general.h" <<'EOF'
#define DOWNLOAD_PROTO_FILE
#define DOWNLOAD_PROTO_HTTPS
#define IMAGE_TRUST_CMD
#define REBOOT_CMD
#define PING_CMD
#define CONSOLE_CMD
#define IMAGE_PNG
#define IMAGE_EFI
#define SANBOOT_CMD
EOF

cat > "$WORKDIR/chain-file.ipxe" <<'EOF'
#!ipxe
chain --autofree file:/embed.ipxe || shell
EOF

echo "==> building ipxe.efi (with file:/embed.ipxe chain)"
make -C "$WORKDIR/ipxe/src" -j"$(nproc)" \
  bin-x86_64-efi/ipxe.efi \
  EMBED="$WORKDIR/chain-file.ipxe"
cp "$WORKDIR/ipxe/src/bin-x86_64-efi/ipxe.efi" "$OUT/ipxe.efi"

echo "==> building or fetching ipxe.lkrn (BIOS; script via isolinux INITRD)"
# Modern binutils often breaks BIOS lkrn link ("final link failed: bad value").
# Prefer a successful local build; otherwise fall back to official binary.
# Stock lkrn is fine: isolinux loads embed.ipxe as INITRD.
if make -C "$WORKDIR/ipxe/src" -j"$(nproc)" bin/ipxe.lkrn; then
  cp "$WORKDIR/ipxe/src/bin/ipxe.lkrn" "$OUT/ipxe.lkrn"
else
  echo "==> local ipxe.lkrn failed; downloading https://boot.ipxe.org/ipxe.lkrn"
  curl -fsSL "https://boot.ipxe.org/ipxe.lkrn" -o "$OUT/ipxe.lkrn"
fi

echo "==> locating syslinux isolinux bits"
copy_syslinux() {
  local iso_bin="$1" ld_bin="$2"
  if [[ -f "$iso_bin" && -f "$ld_bin" ]]; then
    cp "$iso_bin" "$OUT/isolinux.bin"
    cp "$ld_bin" "$OUT/ldlinux.c32"
    return 0
  fi
  return 1
}

if ! copy_syslinux /usr/lib/ISOLINUX/isolinux.bin /usr/lib/syslinux/modules/bios/ldlinux.c32 \
  && ! copy_syslinux /usr/lib/syslinux/isolinux.bin /usr/lib/syslinux/modules/bios/ldlinux.c32; then
  SYSLINUX_VER="6.03"
  echo "==> fetching syslinux ${SYSLINUX_VER} tarball"
  curl -fsSL "https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-${SYSLINUX_VER}.tar.gz" \
    -o "$WORKDIR/syslinux.tar.gz"
  tar -xzf "$WORKDIR/syslinux.tar.gz" -C "$WORKDIR"
  cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/core/isolinux.bin" "$OUT/isolinux.bin"
  cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/com32/elflink/ldlinux/ldlinux.c32" "$OUT/ldlinux.c32"
fi

cat > "$OUT/README.md" <<EOF
# Boot assets

Generated by scripts/build-ipxe-assets.sh in CI.

- \`ipxe.efi\`: built with EMBED chaining \`file:/embed.ipxe\`
- \`ipxe.lkrn\`: local build or boot.ipxe.org fallback (BIOS uses isolinux INITRD)
- \`isolinux.bin\` / \`ldlinux.c32\`: from distro packages or syslinux release
EOF

ls -lh "$OUT"
test -s "$OUT/ipxe.efi"
test -s "$OUT/ipxe.lkrn"
test -s "$OUT/isolinux.bin"
test -s "$OUT/ldlinux.c32"
echo "==> assets ready in $OUT"
