#!/usr/bin/env bash
set -euo pipefail

# Build iPXE / syslinux boot assets for ISO export.
# Intended to run in GitHub Actions (Linux), not on the Windows control laptop.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/assets}"
mkdir -p "$OUT"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> cloning iPXE"
git clone --depth 1 https://github.com/ipxe/ipxe.git "$WORKDIR/ipxe"

# Enable file:// so fallback EFI binary can chain embed.ipxe on the ESP
mkdir -p "$WORKDIR/ipxe/src/config/local"
cat > "$WORKDIR/ipxe/src/config/local/general.h" <<'EOF'
#define DOWNLOAD_PROTO_FILE
#define DOWNLOAD_PROTO_HTTPS
#define IMAGE_TRUST_CMD
#define REBOOT_CMD
#define PING_CMD
#define CONSOLE_CMD
#define IMAGE_PNG
#define IMAGE_EFI
#define SANBOOT_CMD
EOF

cat > "$WORKDIR/chain-file.ipxe" <<'EOF'
#!ipxe
chain --autofree file:/embed.ipxe || chain --autofree file:embed.ipxe || shell
EOF

echo "==> building ipxe.efi (fallback EMBED chains file:/embed.ipxe)"
make -C "$WORKDIR/ipxe/src" -j"$(nproc)" \
  bin-x86_64-efi/ipxe.efi \
  EMBED="$WORKDIR/chain-file.ipxe"
cp "$WORKDIR/ipxe/src/bin-x86_64-efi/ipxe.efi" "$OUT/ipxe.efi"

echo "==> building or fetching ipxe.lkrn (BIOS; script via isolinux INITRD)"
if make -C "$WORKDIR/ipxe/src" -j"$(nproc)" bin/ipxe.lkrn; then
  cp "$WORKDIR/ipxe/src/bin/ipxe.lkrn" "$OUT/ipxe.lkrn"
else
  echo "==> local ipxe.lkrn failed; downloading https://boot.ipxe.org/ipxe.lkrn"
  curl -fsSL "https://boot.ipxe.org/ipxe.lkrn" -o "$OUT/ipxe.lkrn"
fi

echo "==> locating syslinux / isolinux bits"
copy_pair() {
  local iso_bin="$1" ld_bin="$2" mbr_bin="${3:-}"
  if [[ -f "$iso_bin" && -f "$ld_bin" ]]; then
    cp "$iso_bin" "$OUT/isolinux.bin"
    cp "$ld_bin" "$OUT/ldlinux.c32"
    if [[ -n "$mbr_bin" && -f "$mbr_bin" ]]; then
      cp "$mbr_bin" "$OUT/isohdpfx.bin"
    fi
    return 0
  fi
  return 1
}

if ! copy_pair /usr/lib/ISOLINUX/isolinux.bin \
      /usr/lib/syslinux/modules/bios/ldlinux.c32 \
      /usr/lib/ISOLINUX/isohdpfx.bin \
  && ! copy_pair /usr/lib/syslinux/isolinux.bin \
      /usr/lib/syslinux/modules/bios/ldlinux.c32 \
      /usr/lib/syslinux/isohdpfx.bin; then
  SYSLINUX_VER="6.03"
  echo "==> fetching syslinux ${SYSLINUX_VER} tarball"
  curl -fsSL "https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-${SYSLINUX_VER}.tar.gz" \
    -o "$WORKDIR/syslinux.tar.gz"
  tar -xzf "$WORKDIR/syslinux.tar.gz" -C "$WORKDIR"
  cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/core/isolinux.bin" "$OUT/isolinux.bin"
  cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/com32/elflink/ldlinux/ldlinux.c32" "$OUT/ldlinux.c32"
  cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/mbr/isohdpfx.bin" "$OUT/isohdpfx.bin"
fi

# Ensure isohdpfx exists
if [[ ! -f "$OUT/isohdpfx.bin" ]]; then
  for c in /usr/lib/ISOLINUX/isohdpfx.bin /usr/lib/syslinux/isohdpfx.bin /usr/share/syslinux/isohdpfx.bin; do
    if [[ -f "$c" ]]; then
      cp "$c" "$OUT/isohdpfx.bin"
      break
    fi
  done
fi

echo "==> fetching wimboot (Windows ISO)"
# Official iPXE wimboot release
WIMBOOT_VER="2.8.0"
curl -fsSL "https://github.com/ipxe/wimboot/releases/download/v${WIMBOOT_VER}/wimboot" -o "$OUT/wimboot" \
  || curl -fsSL "https://boot.ipxe.org/wimboot" -o "$OUT/wimboot"
chmod +x "$OUT/wimboot"

cat > "$OUT/README.md" <<EOF
# Boot assets

Generated by scripts/build-ipxe-assets.sh in CI.

- \`ipxe.efi\` / \`ipxe.lkrn\` / isolinux / isohdpfx: custom iPXE media export
- \`wimboot\`: Windows installer ISO (BIOS + UEFI)
EOF

ls -lh "$OUT"
test -s "$OUT/ipxe.efi"
test -s "$OUT/ipxe.lkrn"
test -s "$OUT/isolinux.bin"
test -s "$OUT/ldlinux.c32"
test -s "$OUT/isohdpfx.bin"
test -s "$OUT/wimboot"
echo "==> assets ready in $OUT"
