#!/usr/bin/env bash
set -euo pipefail

# Build iPXE / syslinux boot assets for ISO export.
# Intended to run in GitHub Actions (Linux), not on the Windows control laptop.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/assets}"
mkdir -p "$OUT"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> cloning iPXE"
git clone --depth 1 https://github.com/ipxe/ipxe.git "$WORKDIR/ipxe"

# Enable file:// so EFI binary can chain embed.ipxe on the ISO
mkdir -p "$WORKDIR/ipxe/src/config/local"
cat > "$WORKDIR/ipxe/src/config/local/general.h" <<'EOF'
#define DOWNLOAD_PROTO_FILE
#define DOWNLOAD_PROTO_HTTPS
#define IMAGE_TRUST_CMD
#define REBOOT_CMD
#define PING_CMD
#define CONSOLE_CMD
#define IMAGE_PNG
#define IMAGE_EFI
#define SANBOOT_CMD
#define DOWNLOAD_PROTO_NFS
EOF

cat > "$WORKDIR/chain-file.ipxe" <<'EOF'
#!ipxe
iseq ${platform} efi && goto efi || goto bios
:efi
chain --autofree file:/embed.ipxe || shell
:bios
chain --autofree file:/embed.ipxe || shell
EOF

echo "==> building ipxe.lkrn / ipxe.efi"
make -C "$WORKDIR/ipxe/src" -j"$(nproc)" \
  bin/ipxe.lkrn \
  bin-x86_64-efi/ipxe.efi \
  EMBED="$WORKDIR/chain-file.ipxe"

cp "$WORKDIR/ipxe/src/bin/ipxe.lkrn" "$OUT/ipxe.lkrn"
cp "$WORKDIR/ipxe/src/bin-x86_64-efi/ipxe.efi" "$OUT/ipxe.efi"

echo "==> fetching syslinux isolinux bits"
SYSLINUX_VER="6.03"
curl -fsSL "https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-${SYSLINUX_VER}.tar.gz" \
  -o "$WORKDIR/syslinux.tar.gz"
tar -xzf "$WORKDIR/syslinux.tar.gz" -C "$WORKDIR"
cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/core/isolinux.bin" "$OUT/isolinux.bin"
cp "$WORKDIR/syslinux-${SYSLINUX_VER}/bios/com32/elflink/ldlinux/ldlinux.c32" "$OUT/ldlinux.c32"

cat > "$OUT/README.md" <<EOF
# Boot assets

Generated by scripts/build-ipxe-assets.sh in CI.

- ipxe.lkrn / ipxe.efi: built with EMBED that chains \`file:/embed.ipxe\`
- isolinux.bin / ldlinux.c32: from syslinux ${SYSLINUX_VER}
EOF

ls -lh "$OUT"
echo "==> assets ready in $OUT"
